#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@uuplugin[-1]
	add ucitrack uuplugin
	set ucitrack.@uuplugin[-1].init=uuplugin
	commit ucitrack
EOF

chmod +x /etc/init.d/uuplugin
chmod +x /usr/libexec/uuplugin/* 2>/dev/null

rm -f /tmp/luci-indexcache
exit 0
